[build]
  command = "echo $FIREBASE_ADMIN_JSON | base64 --decode > firebase_admin.json && npm install && npm run build && npm run start"
  functions = "api"

[dev]
  framework = "#custom"
  command = "netlify dev"
