[build]
  command = "echo $FIREBASE_ADMIN_JSON | base64 --decode > firebase_admin.json && npm install && npm run build"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
